repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
        types: [yaml]
      - id: check-toml
        types: [toml]
        #          - id: end-of-file-fixer
        #            types: [text]
        stages: [commit, push, manual]
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: fix-encoding-pragma

  - repo: https://github.com/prettier/pre-commit
    rev: 57f39166b5a5a504d6808b87ab98d41ebf095b46
    hooks:
      - id: prettier
